spring.datasource.url=jdbc:postgresql://ep-royal-lake-a1sv82f0-pooler.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_xMEmQdHL37zw&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_xMEmQdHL37zw


# --- SMTP Configuration (Gunakan Gmail & App Password seperti contoh sebelumnya) ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bidmart.b11@gmail.com
spring.mail.password=xfqz ugni htoe hcgr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# --- Custom Email Properties (Sesuai dengan kode Anda) ---
app.email.from=noreply@bidmart.com
app.email.verification-subject=Verifikasi Akun BidMart Anda
# Ganti localhost:8080 sesuai port aplikasi Anda
app.email.verification-url-template=http://localhost:8080/api/auth/verify?token=